### ISSUE TITLE
"Rank" database field vs. deterministic instance method

### ISSUE THREAD

**Issue by legaultmarc** [legaultmarc/genomenews#3]
I think the ``news.models.Post.set_rank()`` method should be replaced by a ``news.models.Post.rank()`` method that computes it on the fly.

This is to avoid redundancy in the database as the ranking algorithm is a deterministic function of the karma and age. The parameter (gravity) could become an optional argument of the method to allow for fine tuning in production without needing to mess with the database.

Another advantage would be to only have to update the ``karma`` field without worrying about database discrepancies.

Let me know what you think (@maclandrol).

**Comment by maclandrol** [comment]
I agree. You're right!
