### ISSUE TITLE
Header not inline

### ISSUE THREAD

**Issue by maclandrol** [legaultmarc/genomenews#4]
When the user logout and refresh the page. This happen. The display should be inline.

![image](https://cloud.githubusercontent.com/assets/5290110/5671209/113e9e2c-9754-11e4-818d-884a1a8f6192.png)

![image](https://cloud.githubusercontent.com/assets/5290110/5671218/1fe467b8-9754-11e4-89bc-527eba088d12.png)

**Comment by legaultmarc** [comment]
Are you talking about the left margin on content or about the ``login | register`` in the top right corner?

**Comment by legaultmarc** [comment]
I am going crazy over this. It appears only because of the <form>. I have no idea why.

**Comment by legaultmarc** [comment]
Also, this doesn't happen on Firefox and Safari...

**Comment by maclandrol** [comment]
I was already suspicious about django default form rendering. Maybe it a better idea to break it into div or a table and control the rendering ourselves.
